# Generated by Django 5.1.4 on 2025-06-22 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories_per_unit',
            field=models.FloatField(help_text='Enter the calories per unit of measurement'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Enter the name of the food item', max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('grams', 'Grams'), ('pieces', 'Pieces'), ('cups', 'Cups'), ('ml', 'Milliliters'), ('servings', 'Servings'), ('tablespoons', 'Tablespoons'), ('teaspoons', 'Teaspoons')], default='grams', help_text='Select the unit of measurement', max_length=50),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select the date when this meal was consumed'),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], help_text='Select when this meal was consumed', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='quantity',
            field=models.FloatField(help_text='Enter the quantity in the selected unit'),
        ),
    ]
