# Generated by Django 5.1.4 on 2025-06-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_food_calories_per_unit_alter_food_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='quantity',
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Enter the quantity in the selected unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.mealentry')),
            ],
        ),
    ]
